### ISSUE TITLE
requirements of pyarrow>=0.11.1,<0.17.0 are very narrow

### ISSUE THREAD

**Issue by antoncrombach** [aertslab/ctxcore#3]
Hi,

as I tried to install pySCENIC under Python 3.9, I ran into troubles with the required version of `pyarrow`. As `pyarrow` is now at version 5.0.0, perhaps it is possible to relax the upper bound of 0.17.0?

In any case, my naive solution to get the package `ctxcore` to install, is to remove the "<0.17.0" part in `requirements.txt`. It does not seem to break things, but given my scarce knowledge of ctxcore, I wonder if there are any unintended consequences?

Any thoughts?
Cheers!

**Comment by ghuls** [comment]
It probably will break stuff.

pyarrow "<0.17.0" was the last version that allowed an easy way to read column names of a Feather file without reading the whole file first. (Only for Feather v2 format they have a relative easy way to get the column names. For Feather v1, I had to reimplement it myself.

https://github.com/aertslab/create_cisTarget_databases/blob/master/feather_v1_or_v2.py

Code from https://github.com/aertslab/create_cisTarget_databases/ will replace the database reading code in rnkdb.py one day.

**Comment by antoncrombach** [comment]
Okay, thanks for lifting the bonnet and explaining what the rationale is. I reverted to Python 3.7 and `ctxcore` installs smoothly.

**Comment by KrotosBenjamin** [comment]
Hello,

I had the same issue with Python 3.9 and found this very helpful. It would be even better if the python version that this works with is **included in pypi/README/documentation**, so that people know ahead of time. 

Thanks for you work.

**Comment by ghuls** [comment]
Next version will work with pyarrow 8.0.0:
https://github.com/aertslab/ctxcore/tree/update_pyarrow

**Comment by ghuls** [comment]
New version is published: https://github.com/aertslab/ctxcore/releases/tag/0.2.0
